version: "3"

volumes:
  users-postgres-data:
    driver: local

services:
  #
  # USERS SERVICE
  #
  users-postgres:
    container_name: postgres
    image: postgres
    volumes:
      - users-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  users-api:
    container_name: users-api
    build: .
    ports:
      - "5020:5020"
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@users-postgres:5432/postgres?sslmode=disable
      - PORT=5020
    depends_on:
      - users-postgres
    links:
      - users-postgres
